import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import contactsRouter from "./contacts";
import productsRouter from "./products";
import dealsRouter from "./deals";
import activitiesRouter from "./activities";
import reportsRouter from "./reports";
import importRouter from "./import";
import categoriesRouter from "./categories";
import proformaInvoicesRouter from "./proforma-invoices";
import customerMasterRouter from "./customer-master";
import notificationsRouter from "./notifications";
import dashboardRouter from "./dashboard";
import documentsRouter from "./documents";
import gstRouter from "./gst";
import productionRouter from "./production";
import ordersRouter from "./orders";
import quotationsRouter from "./quotations";
import batchesRouter from "./batches";
import dispatchRouter from "./dispatch";
import complaintsRouter from "./complaints";
import communicationsRouter from "./communications";
import notesRouter from "./notes";
import auditLogsRouter from "./audit-logs";
import searchRouter from "./search";
import existingCustomersRouter from "./existing-customers";
import exportsRouter from "./exports";
import transportLogisticsRouter from "./transport-logistics";
import transportMastersRouter from "./transport-masters";
import unitsRouter from "./units";
import inventoryRouter from "./inventory";
import voiceNotesRouter from "./voice-notes";
import importEngineRouter from "./import-engine";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(contactsRouter);
router.use(productsRouter);
router.use(dealsRouter);
router.use(activitiesRouter);
router.use(reportsRouter);
router.use(importRouter);
router.use(categoriesRouter);
router.use(proformaInvoicesRouter);
router.use(customerMasterRouter);
router.use(notificationsRouter);
router.use(dashboardRouter);
router.use(documentsRouter);
router.use(gstRouter);
router.use(productionRouter);
router.use(ordersRouter);
router.use(quotationsRouter);
router.use(batchesRouter);
router.use(dispatchRouter);
router.use(complaintsRouter);
router.use(communicationsRouter);
router.use(notesRouter);
router.use(auditLogsRouter);
router.use(searchRouter);
router.use(existingCustomersRouter);
router.use(transportLogisticsRouter);
router.use(transportMastersRouter);
router.use(unitsRouter);
router.use(inventoryRouter);
router.use(voiceNotesRouter);
router.use(importEngineRouter);
router.use("/exports", exportsRouter);

export default router;
