ALTER TABLE products ADD COLUMN IF NOT EXISTS material_type TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS hsn_code TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS default_unit TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS default_gst NUMERIC(5, 2);
